source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

def pods

pod 'Alamofire', '2.0.2'
pod 'MBProgressHUD', '~> 0.9.0'
pod 'Kanna', '~> 1.0.5'
pod 'Kingfisher', '~> 2.0.1'
pod 'Mantle', '~> 2.0.6'
pod 'ReactiveViewModel'
pod 'Fabric'
pod 'Crashlytics'
pod 'UMengAnalytics-NO-IDFA'
end

target 'Girls' do
    pods
end
